server:
  port: 5002
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_TRACE_PARAM
    include-exception: true
spring:
 application:
   name: cdo-employees
 authorization:
   admin:
     role: ADMIN
   manager:
     role: ADMIN,MANAGER
   cdm:
     role: ADMIN,MANAGER,CDM
   user:
     role: ADMIN,MANAGER,CDM,USER,EMPLOYEE
 jpa:
   hibernate:
   #ddl-auto: create
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
 messages:
   basename: messages
 servlet:
   multipart:
     enabled: true
     file-size-threshold: 2KB
     max-file-size: 200MB
     max-request-size: 215MB
reflectoring:
 trace: true
crm:
 admin:
   email: sti2k.hai.ly@gmail.com
   name: admin
   password: 12345678
 jwt:
   expiration-millis: 864000000
   secret: JWTLOGIGEAR_CRM_SuperSecretKey
   short-lived-millis: 120000
 upload-dir: ./file
---
spring:
    profiles: dev
    datasource:
        password: Abcd1234
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
---
spring:
    profiles: deployment
    datasource:
        password: ${POSTGRES_PW}
        url: ${POSTGRES_URL}
        username: ${POSTGRES_UN}