package com.logigear.crm.admins.util;

import lombok.SneakyThrows;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

/**
 * This class intended for image file uploading to the hard disk.
 **/
@Component
public class FileUploadUtil {

    private static final File IMAGE_SAVE_FOLDER = new File("image");
    private static final String IMAGE_FILE_EXTENSION = ".png";

    /**
     * Write the image content to the disk
     *
     * @param fileName      The image name generated by the service
     * @param multipartFile The image content
     * @throws IOException When the image saving error to the disk (disk security, full disk)
     * @author bang.ngo
     **/
    @SneakyThrows(IOException.class)
    public void writePNGImageFileToDisk(String fileName, MultipartFile multipartFile) {
        Path uploadPath = Paths.get(IMAGE_SAVE_FOLDER.getPath());
        if (!Files.exists(uploadPath)) {
            Files.createDirectories(uploadPath);
        }
        try (InputStream inputStream = multipartFile.getInputStream()) {
            Path filePath = uploadPath.resolve(fileName);
            Files.copy(inputStream, filePath, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ioe) {
            throw new IOException("Could not save image file: " + fileName, ioe);
        }
    }

    /**
     * Get the prepared image file name with the associated employee id
     *
     * @param employeeId The associated employee id
     * @return Generated image file name
     * @author bang.ngo
     **/
    public String getPreparedImageFileNameWithAssociatedEmployeeId(String employeeId) {
        //Fix: Get a random file name based on UUID.
        // Because UUID is just matched 32 chars after removing - char.
        return employeeId + "_" + IDGeneratorUtil.getRandom32CharUUIDString() + IMAGE_FILE_EXTENSION;
    }
}